language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
cache: pip

install:
  - wget -O confindr_integration.tar.gz https://ndownloader.figshare.com/files/14773226 && tar xf confindr_integration.tar.gz
  - wget https://sourceforge.net/projects/bbmap/files/BBMap_37.68.tar.gz
  - tar xf BBMap_37.68.tar.gz
  - export PATH=$PATH:$PWD/bbmap/
  - wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar
  - tar xf mash-Linux64-v2.0.tar
  - export PATH=$PATH:$PWD/mash-Linux64-v2.0
  - git clone https://bitbucket.org/genomicepidemiology/kma.git
  - cd kma && make
  - cd ..
  - export PATH=$PATH:$PWD/kma
  - pip install -e .
branches:
  only:
    - master

script:
  - pytest tests/test_confindr.py
