language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
cache: pip

install:
  - wget -O confindr_integration.tar.gz https://ndownloader.figshare.com/files/14773226 && tar xf confindr_integration.tar.gz
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install -c bioconda -c conda-forge bbmap biopython kma mash minimap2 pluggy pysam pytest rauth samtools
  - pip install -e .
branches:
  only:
    - master

script:
  - conda activate test-environment
  - travis_wait 30 pytest tests/test_confindr.py
