language: python
python:
  - '3.5'
cache: pip

install:
  - pip install -r requirements.txt
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz
  - tar xf jellyfish-2.2.6.tar.gz
  - pushd jellyfish-2.2.6 && ./configure --prefix /usr && make && sudo make install && popd
  - wget https://sourceforge.net/projects/bbmap/files/BBMap_37.68.tar.gz
  - tar xf BBMap_37.68.tar.gz
  - export PATH=$PATH:$PWD/bbmap/
  - wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar
  - tar xf mash-Linux64-v2.0.tar
  - export PATH=$PATH:$PWD/mash-Linux64-v2.0
  - sudo apt install ncbi-blast+
  - wget https://ndownloader.figshare.com/files/9827251 && tar xf 9827251
branches:
  only:
    - master

script:
  - pytest tests/test_confindr.py
