language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
cache: pip

install:
  - wget https://sourceforge.net/projects/bbmap/files/BBMap_37.68.tar.gz
  - tar xf BBMap_37.68.tar.gz
  - export PATH=$PATH:$PWD/bbmap/
  - wget https://github.com/marbl/Mash/releases/download/v2.0/mash-Linux64-v2.0.tar
  - tar xf mash-Linux64-v2.0.tar
  - export PATH=$PATH:$PWD/mash-Linux64-v2.0
  - pip install -e .
branches:
  only:
    - master

script:
  - pytest tests/test_confindr.py
